os: Windows Server 2012

environment:
  global:
    EnableNuGetPackageRestore:true
    
build_script:
  - "set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\" 
  - fsi --exec build.fsx BuildTest
  
test:
  assemblies:
    - test/build/Test.dll
